### ISSUE TITLE
Tmdb ID for shows

### ISSUE THREAD

**Issue by IgnisDa** [shemanaev/jellyfin-plugin-webhooks#5]
Hey, thanks for this project! I noticed that the default webhook does not send the tmdb ID for shows:
![image](https://github.com/shemanaev/jellyfin-plugin-webhooks/assets/60938164/52ab3ae1-3d40-4f49-987b-ed0b0422f681)

But it does so for movies:
![image](https://github.com/shemanaev/jellyfin-plugin-webhooks/assets/60938164/8b279d96-5720-408b-b293-6500dd524374)

Would this be possible to add this?

**Comment by IgnisDa** [comment]
I am writing an integration for https://github.com/ignisda/ryot with Jellyfin. In that, a specific episode can be marked as seen.

> doesn't have id for specific episodes

Actually, I just need it to be the ID of the show, can figure out the rest from the rest of the payload. Will that be possible to add?

**Comment by IgnisDa** [comment]
That'd be great! Thanks!

**Comment by shemanaev** [comment]
Released new version with optional `Series` field in payload. Update plugin as usual via Jellyfin.
