### ISSUE TITLE
Episode numbers for TV shows

### ISSUE THREAD

**Issue by IgnisDa** [shemanaev/jellyfin-plugin-webhooks#6]
The `Pause` event for this webhook (with Default format) gives this payload: https://pastebin.com/hkL6CnW2.

As you can see, it does not contain details about the Season Number (1 here, just contains `SeasonName` which is a string) and Episode Number (1 here). Can this be added to the payload?

EDIT: It does contain `SortName: 001 - 0001 - <Name>` which might work but I am not sure what it is.

**Comment by shemanaev** [comment]
Season - `ParentIndexNumber`
Episode - `IndexNumber`
