### ISSUE TITLE
`PlaybackPositionTicks` not giving correct value

### ISSUE THREAD

**Issue by IgnisDa** [shemanaev/jellyfin-plugin-webhooks#7]
When the movie is about 90% done (or more notably, when `Played` becomes `true`), the value of `PlaybackPositionTicks` is set to 0. I expect it to be the current value of the timer on the player. Same for `PlayedPercentage` which disappears after the movie is 90% done.

I believe that they should be giving me the exact values.

**Comment by shemanaev** [comment]
AFAIK that's the feature of Jellyfin itself. It can be configured in Dashboard -> Playback -> Resume -> Maximum resume percentage

**Comment by IgnisDa** [comment]
Would it be possible for you to add the exact playback tick to the payload regardless of the above setting?

**Comment by shemanaev** [comment]
Added `Session.PositionTicks` to payload in new version. Percentage will be `Session.PositionTicks / Item.RunTimeTicks * 100` respectively.
Please report back if it will be enough.
