### ISSUE TITLE
Event for playback progress

### ISSUE THREAD

**Issue by IgnisDa** [shemanaev/jellyfin-plugin-webhooks#9]
It would be great if a webhook be triggered when there is progress in playback. The official jellyfin plugin does this.

**Comment by IgnisDa** [comment]
@shemanaev Any updates on this?

**Comment by IgnisDa** [comment]
Cool thanks!

**Comment by shemanaev** [comment]
Released update. Feel free to reopen if it ain't gonna work 😄

**Comment by IgnisDa** [comment]
Thanks, it works!
